### ISSUE TITLE
Android crashes

### ISSUE THREAD

**Issue by renatomserra** [mouselangelo/react-native-actions-shortcuts#54]
Hellow!

Thank you for developing this.
On android im getting a couple crashes a day with a few hundred DAU with the following

```
Fatal Exception: java.lang.RuntimeException: Could not invoke RNShortcuts.setShortcuts
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:203)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:761)
 ```

Any idea what it could be?

**Comment by Magnus-V** [comment]
Experiencing the same for android 7.x users
